---
name: Testing

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  gotest:
    name: Go ${{ matrix.go }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.19", "1.20"]
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3.5.3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./... -race -coverprofile=coverage.out -covermode=atomic
      - name: ⬆️ Upload coverage artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: coverage-${{ matrix.go }}
          path: coverage.out

  coverage:
    runs-on: ubuntu-latest
    needs: gotest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - name: ⬇️ Download coverage data
        uses: actions/download-artifact@v3.0.2
      - name: 🚀 Upload coverage report
        uses: codecov/codecov-action@v3.1.4
      - name: SonarCloud Scan
        if: github.event.pull_request.head.repo.fork == false
        uses: SonarSource/sonarcloud-github-action@v1.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
